version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hlola-grc-db-prod
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hlola_grc_platform
      POSTGRES_USER: hlola_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_this_in_production}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hlola_user -d hlola_grc_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - grc-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_prod_data:
    name: hlola_grc_postgres_prod_data
    driver: local

networks:
  grc-network:
    name: hlola_grc_network
    driver: bridge
